
import java.awt.Color;
import java.util.logging.Level;
import java.util.logging.Logger;
import java.util.regex.Matcher;
import java.util.regex.Pattern;
import javax.swing.JTextArea;
import javax.swing.text.BadLocationException;
import javax.swing.text.DefaultHighlighter;
import javax.swing.text.Highlighter;

/**
 * Finestra di dialogo per cercare testo
 * @see Highlighter
 */
public class SearchDialog extends javax.swing.JDialog {

    JTextArea txtCode;
    Highlighter highlighter;
    int index;
    /**
     * Inizializza i componenti grafici
     * @param parent Finestra madre
     * @param modal Modalità di apertura
     * @param txtCode Casella di testo
     * @see Highlighter
     */
    public SearchDialog(java.awt.Frame parent, boolean modal, JTextArea txtCode) {
        super(parent, modal);
        initComponents();
        this.txtCode = txtCode;
        highlighter = txtCode.getHighlighter();
        index=0;
    }
    
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnCerca = new javax.swing.JButton();
        btnAnnulla = new javax.swing.JButton();
        txtCerca = new javax.swing.JTextField();
        btnTrova = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });

        btnCerca.setText("Cerca");
        btnCerca.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCercaActionPerformed(evt);
            }
        });

        btnAnnulla.setText("Annulla");
        btnAnnulla.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAnnullaActionPerformed(evt);
            }
        });

        btnTrova.setText("Trova successivo");
        btnTrova.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTrovaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 55, Short.MAX_VALUE)
                        .addComponent(btnCerca)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnTrova)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnAnnulla))
                    .addComponent(txtCerca))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addComponent(txtCerca, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnCerca)
                    .addComponent(btnAnnulla)
                    .addComponent(btnTrova))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    /**
     * Cerca e evidenzia tutti i testi corrispondente al testo inserito
     * @param evt evento click dell'opzione Cerca
     * @see Highlighter
     */
    private void btnCercaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCercaActionPerformed
        String search = txtCerca.getText();
        highlighter.removeAllHighlights();
        index=0;
        if (!search.equals(""))
        {                    
            DefaultHighlighter.DefaultHighlightPainter painter = new DefaultHighlighter.DefaultHighlightPainter(Color.CYAN);                 
            Pattern pattern = Pattern.compile( Pattern.quote(search) );
            Matcher matcher = pattern.matcher(txtCode.getText());                    

            while(matcher.find()) {
                try {
                    highlighter.addHighlight(matcher.start(), matcher.end(), painter);                    
                } catch (BadLocationException ex) {
                    Logger.getLogger(SearchDialog.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        }        
        
    }//GEN-LAST:event_btnCercaActionPerformed

    /**
     * Rimuove tutte le evidenziazione e chiude la finestra 
     * @param evt evento click dell'opzione Annulla
     * @see Highlighter
     */
    private void btnAnnullaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAnnullaActionPerformed
        highlighter.removeAllHighlights();
        this.dispose();
    }//GEN-LAST:event_btnAnnullaActionPerformed

    /**
     * Rimuove tutte le evidenziazione e chiude la finestra 
     * @param evt evento chiusura finestra
     * @see Highlighter
     */
    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        highlighter.removeAllHighlights();
    }//GEN-LAST:event_formWindowClosing

    /**
     * Cerca e evidenzia il testo corrispondente al testo inserito<br>
     * Ogni volta che viene schiacciato il pultante "Trova successivo" evidenzia il prossimo testo corrispondente
     * @param evt evento click dell'opzione Trova successivo
     * @see Highlighter
     */
    private void btnTrovaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTrovaActionPerformed
        String search = txtCerca.getText();
        highlighter.removeAllHighlights();        
        if (!search.equals(""))
        {                    
            DefaultHighlighter.DefaultHighlightPainter painter = new DefaultHighlighter.DefaultHighlightPainter(Color.yellow);                 
            Pattern pattern = Pattern.compile( Pattern.quote(search) );
            Matcher matcher = pattern.matcher(txtCode.getText());                    
            if (matcher.find(index)){
                try {
                    highlighter.addHighlight(matcher.start(), matcher.end(), painter);
                    index=matcher.end();
                    txtCode.setCaretPosition(matcher.start());
                } catch (BadLocationException ex) {
                    Logger.getLogger(SearchDialog.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
            else 
            {
                index=0;
                matcher.find(index);
                try {
                    highlighter.addHighlight(matcher.start(), matcher.end(), painter);
                    index=matcher.end();
                    txtCode.setCaretPosition(matcher.start());
                } catch (BadLocationException ex) {
                    Logger.getLogger(SearchDialog.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        }
    }//GEN-LAST:event_btnTrovaActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAnnulla;
    private javax.swing.JButton btnCerca;
    private javax.swing.JButton btnTrova;
    private javax.swing.JTextField txtCerca;
    // End of variables declaration//GEN-END:variables
}
